<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Medicine;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run()
    {
        foreach ($this->medicines() as $medicine) {
            Medicine::create([
                'name' => $medicine['name'],
                'details' => $medicine['details'],
                'price' => $medicine['price'],
                'selling_price' => $medicine['selling_price'],
                'quantity' => rand(50, 200),
                'type_id' => $medicine['type_id'],
                'supplier_id' => rand(1, 30),
                'unit_id' => $medicine['unit_id'],
                'category_id' => $medicine['category_id'],
                'measurement' => $medicine['measurement'],
                'barcode_number' => rand(000000000001, 100000000000),
                'is_prescribed' => $medicine['is_prescribed'],
                'expired_at' => Carbon::now()->addYears(1),
            ]);
        }
    }

    protected function medicines()
    {
        return [
            [
                'name' => 'Amoxicillin',
                'details' => 'Amoxicillin is an antibiotic used to treat a number of bacterial infections.',
                'price' => '4.50',
                'selling_price' => '5.70',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'Mefenamic Acid',
                'details' => 'Mefenamic acid is used to relieve mild to moderate pain, including menstrual pain (pain that happens before or during a menstrual period).',
                'price' => '4.60',
                'selling_price' => '5.70',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'barcode_number' => '000002340091',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'Paracetamol',
                'details' => '',
                'price' => '3.20',
                'selling_price' => '4',
                'type_id' => '2',
                'unit_id' => '5',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Decolgen',
                'details' => '',
                'price' => '6',
                'selling_price' => '6.50',
                'type_id' => '2',
                'unit_id' => '5',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Brufen Tablet',
                'details' => '',
                'price' => '7.4',
                'selling_price' => '8',
                'type_id' => '2',
                'unit_id' => '5',
                'category_id' => '2',
                'measurement' => '400',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'Betadine 10%',
                'details' => '',
                'price' => '89.90',
                'selling_price' => '93.50',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '6',
                'measurement' => '15',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Betaloc',
                'details' => '',
                'price' => '8',
                'selling_price' => '9.50',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '25',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Ibufrofen 200mg',
                'details' => '',
                'price' => '5.70',
                'selling_price' => '7',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '200',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Ibufrofen 500mg',
                'details' => '',
                'price' => '6',
                'selling_price' => '7.50',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Bioflu',
                'details' => '',
                'price' => '4.75',
                'selling_price' => '6.50',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Berocca Effervescent Tablet Orange Flavor 30s',
                'details' => 'Performance contains a specific combination of B-Vitamins, Vitamin C enhanced with added Calcium, Magnesium and Zinc. These ingredients work in synergy to help your body release the maximum energy from the food you eat. Berocca?, Performance is the healthy way to sustain your optimal performance throughout the day.',
                'price' => '512',
                'selling_price' => '523',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '1',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'XELENT Cefaclor Monohydrate',
                'details' => '',
                'price' => '658',
                'selling_price' => '667.50',
                'type_id' => '6',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '5',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'DUOMAX Rifampicin',
                'details' => 'Indicated for the continuation phase of short-course treatment of patients with pulmonary or extra-pulmonary tuberculosis.',
                'price' => '9.82',
                'selling_price' => '10.89',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '150',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'KLARICID Clarithromycin',
                'details' => '',
                'price' => '233.04',
                'selling_price' => '245',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'Sultamicillin tosylate',
                'details' => 'For the treatment of infections where lactamase-producing organisms might occur including uncomplicated gonorrhea, otitis media, resp tract infections, and urinary tract infections.',
                'price' => '50.75',
                'selling_price' => '53.40',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '750',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'D-alpha-Tocopherol Lecithin 200IU/500mg Softgel Capsule',
                'details' => '',
                'price' => '100',
                'selling_price' => '120',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '1',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Bundle Pack Of Glutathione With Free Pack Of 10s',
                'details' => 'Cosmo Skin Glutathione is formulated with Higher Dose of 500 mg Glutathione Plus Alpha Lipoic Acid and Vitamin C. Glutathione is a Master Antioxidant and a safe and effective way of skin whitening. Cosmo Cee- is the only Natural- Non Synthetic- Non Acidic Form of Vitamin C in the Philippine Market formulated with Citrus Bioflavonoids plus Sodium Ascorbate',
                'price' => '2079',
                'selling_price' => '2095',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Snow L-Glutathione 1 Capsule',
                'details' => 'SnowCaps L-Glutathione capsule is one of the most potent forms of this amazing enzyme available in the market today.',
                'price' => '1492.50',
                'selling_price' => '1510.50',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '1',
                'measurement' => '500',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'Acai Berry 2 Bottles',
                'details' => '',
                'price' => '920',
                'selling_price' => '245',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '1',
                'measurement' => '650',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Active Multivitamins + Iron 30 Film-Coated Tablets',
                'details' => 'Iberet Active is the only iron supplement that , contains 105 mg elemental iron, Vitamin C, B-complex, and Gradumet Technology to efficiently absorb iron and decrease gastric irritation.',
                'price' => '915',
                'selling_price' => '945',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '1',
                'measurement' => '500',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'Calcium With Vitamin D Softgel 30 Softgel Capsules',
                'details' => 'ATC Calcium with Vitamin D3 helps prevent osteoporosis and dental problems by keeping bones and teeth strong and healthy. According to studies, Calcium plays an essential role in nerve and muscle function while Vitamin D3 helps promote the absorption of calcium and phosphorus and assists in the assimilation of Vitamin A.',
                'price' => '174.50',
                'selling_price' => '167.50',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '1',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Methyl Salicylate + Camphor + Menthol + Turpentine Oil + Eucalyptus Oil Regular',
                'details' => '',
                'price' => '92.50',
                'selling_price' => '95',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '100',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'AQUA MARIS 100% Natural Nasal Spray Classic 30ml',
                'details' => '',
                'price' => '385',
                'selling_price' => '389',
                'type_id' => '7',
                'unit_id' => '1',
                'category_id' => '3',
                'measurement' => '30',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'RITEMED Loratadine Tablet',
                'details' => '',
                'price' => '19.25',
                'selling_price' => '21.25',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '3',
                'measurement' => '10',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'DIMETAPP Syrup',
                'details' => 'For the temporary relief of nasal and sinus congestion including runny nose, sneezing, itching of nose or throat, itchy watery eyes due to cold, flu, hay fever, allergic rhinitis or other respiratory allegies.',
                'price' => '106.75',
                'selling_price' => '110',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'SOLMUX Carbocisteine Pedia Suspension 200mg X 60mL',
                'details' => '',
                'price' => '108',
                'selling_price' => '117',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Ascof Lagundi for Adults 600mg/5mL Menthol-Flavored Syrup 5mL/Sachet',
                'details' => '',
                'price' => '17.50',
                'selling_price' => '21',
                'type_id' => '1',
                'unit_id' => '2',
                'category_id' => '3',
                'measurement' => '600',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Coleus Amboinicus Lour (Oregano) Leaf Syrup Expectorant',
                'details' => 'Herbycin is a natural cough remedy syrup prepared from fresh, healthy, and clean Oregano leaves, a medicinal plant known for its expectorant and antibacterial properties.
',
                'price' => '129.26',
                'selling_price' => '134',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '120',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Phenylephrine HCl 2.5mg Chlorphenamine Maleate 0.5mg Drops 10 mL',
                'details' => '',
                'price' => '116',
                'selling_price' => '124',
                'type_id' => '4',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '10',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Diphenhydramine',
                'details' => 'For relief of symptoms associated with seasonal, perennial vasomotor rhinitis. Allergic conjunctivitis. Mild, uncomplicated allergic skin manifestations of urticaria and angioedema.',
                'price' => '8.75',
                'selling_price' => '10',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '50',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'DISUDRIN Syrup 60mL',
                'details' => 'For the relief of clogged & runny nose, postnasal drip, itchy, watery eyes & other minor resp tract infections. Helps decongest sinus openings & passages.',
                'price' => '117',
                'selling_price' => '124',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Pedia Syrup 100mg X 120mL',
                'details' => 'For adjunct therapy for chronic disorder of the respiratory tract associated with excessive or viscous mucus.',
                'price' => '162',
                'selling_price' => '166',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '10',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'CarbocisteinePedia Suspension 100mg X 60mL',
                'details' => '',
                'price' => '106.5',
                'selling_price' => '117.5',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '100',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'NEO BROMEXAN Forte 1 Capsule',
                'details' => 'For the relief of nasal congestion, headache and fever associated with sinusitis, common cold and allergy.',
                'price' => '11.5',
                'selling_price' => '14.5',
                'type_id' => '1',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'Disudrin Phenylephrine HCl 5mg Chlorphenamine Maleate 1 mg Syrup',
                'details' => '',
                'price' => '176',
                'selling_price' => '180',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '120',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'RITEMED Dextromethorphan 10mg/5mL Syrup x60mL',
                'details' => '',
                'price' => '60',
                'selling_price' => '65',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'WOODS Cough Medicine 5 Plus 1 sachet',
                'details' => 'Woods Throat Solution provides efficacious and instant soothing relief for non-productive cough caused by the common cold, flu, allergies, or hay fever',
                'price' => '62.5',
                'selling_price' => '64.5',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '20',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'PLEMEX Vitex negundo 300mg/5mL Syrup 60mL',
                'details' => '',
                'price' => '104',
                'selling_price' => '110',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'ORAMEDY Alis Singaw Ointment 6g',
                'details' => 'For chronic exfoliated gingivitis, Obstinate stomatitis and Glossittis with erosive and ulcerative lesion.',
                'price' => '289',
                'selling_price' => '297',
                'type_id' => '1',
                'unit_id' => '3',
                'category_id' => '6',
                'measurement' => '6',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'RITEMED Diphenhydramine 12.5mg/5mL Elixir x60mL',
                'details' => 'For the relief of symptoms associated with seasonal, perennial, vasomotor rhinitis, allergic conjunctivitis due to foods, parkinsonism (including drug-induced), short-term management of insomnia.',
                'price' => '81',
                'selling_price' => '88',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'NEOZEP Phenylephrine hydrochloride Chlorphenamine maleate Paracetamol 1 Tablet',
                'details' => 'Relief of clogged nose, post nasal drip, headache, body aches & fever associated with common cold, sinusitis, flu & other minor resp tract infections, decongest sinus openings & passages',
                'price' => '5.75',
                'selling_price' => '6.75',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '500',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'STREPSILS Cool Blister Pack 24s',
                'details' => '',
                'price' => '178.25',
                'selling_price' => '180.25',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '1.2',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'SINECOD Butamirate Citrate 50mg 1 Tablet',
                'details' => 'Sinecod Forte is used for symptomatic treatment of cough of various origins.',
                'price' => '22.50',
                'selling_price' => '23.50',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '50',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'ROBITUSSIN Guaifenesin 100mg/5mL Expectorant Syrup x120mL',
                'details' => 'For symptomatic relief from congested chests which may be associated with common cold and increase the flow of natural secretions along the lower respiratory tract. Reduction of sticky phlegm.',
                'price' => '141',
                'selling_price' => '145',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '120',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'DISUDRIN Syrup 60mL',
                'details' => '',
                'price' => '117',
                'selling_price' => '120',
                'type_id' => '1',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'VICKS Vaporub 25g with Ready Display Box',
                'details' => 'Used to temporarily relieve cough due to minor throat and bronchial irritation associated with the common cold when applied to chest and throat. When applied to muscles and joints, temporarily relieves minor aches and pains of muscles.',
                'price' => '94',
                'selling_price' => '96',
                'type_id' => '1',
                'unit_id' => '3',
                'category_id' => '6',
                'measurement' => '25',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'SYMDEX Paracetamol Phenylpropanolamine HCl Chlrophenamine maleate',
                'details' => 'Used in the relief of symptoms associated with common colds including headache, allergic rhinitis, and sinusitis.',
                'price' => '4.25',
                'selling_price' => '5.25',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '325',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'TUSERAN Dextromethorpan Hydrobromide + Phenylpropanolamine Hydrochloride + Paracetamol',
                'details' => '',
                'price' => '41',
                'selling_price' => '45',
                'type_id' => '5',
                'unit_id' => '1',
                'category_id' => '2',
                'measurement' => '60',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'DECOLSIN Dextromethorphan hydrobromide',
                'details' => '',
                'price' => '12.25',
                'selling_price' => '14.25',
                'type_id' => '2',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '365',
                'is_prescribed' => '1',
            ],
            [
                'name' => 'MUCOSOLVAN',
                'details' => 'For the treatment of tracheobronchitis, emphysema with bronchitis pneumoconiosis, chronic inflammatory pulmonary conditions, bronchiectasis, bronchitis with bronchospasm asthma.',
                'price' => '18.75',
                'selling_price' => '20.75',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '30',
                'is_prescribed' => '0',
            ],
            [
                'name' => 'PROPAN Buclizine HCI Multivitamins Mineral 120ml',
                'details' => '',
                'price' => '594.75',
                'selling_price' => '594.75',
                'type_id' => '5',
                'unit_id' => '2',
                'category_id' => '2',
                'measurement' => '30',
                'is_prescribed' => '1',
            ],
        ];
    }
}
